[build]
  command = "cd static-site && npm install && npm run build"
  publish = "static-site"

[build.environment]
  NEXTAUTH_URL = "https://prep-academy.netlify.app"
  NEXTAUTH_SECRET = "nuet-prep-academy-secret-key-2024"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
