[build]
  command = "echo 'Static site ready'"
  publish = "public"

[build.environment]
  NEXTAUTH_URL = "https://prep-academy.netlify.app"
  NEXTAUTH_SECRET = "nuet-prep-academy-secret-key-2024"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200